### upload image
POST http://localhost:8000/upload
Content-Type: application/octet-stream
Accept: application/json

< ./test2.jpg

### ขอผลเป็นรูป JPEG (ตีกรอบแล้ว)
POST http://localhost:8000/infer?render=true
Content-Type: application/octet-stream
Accept: image/jpeg

< ./test2.jpg


### ขอผลเป็น JSON (ไม่ตีกรอบ)
POST http://localhost:8000/infer
Content-Type: application/octet-stream
Accept: application/json

< ./test2.jpg    

