### upload image
POST http://localhost:8000/upload
Content-Type: application/octet-stream
Accept: application/json

< ./test2.jpg


### list images
GET http://localhost:8000/images
Accept: application/json

### JSON response
GET http://localhost:8000/infer/images.jpg

### Rendered image response
GET http://localhost:8000/infer/images.jpg?render=true

### get with header for api key
GET https://api.openaq.org/v3/locations/2178
X-API-Key: 91946d8c9baab82d4509077be0f7d1919ddacff90fd121c457af96841edb4f35